
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS site_name text NOT NULL DEFAULT 'SHORTSAL',
  ADD COLUMN IF NOT EXISTS site_tagline text NOT NULL DEFAULT 'The next-generation short video platform for creators worldwide.',

  ADD COLUMN IF NOT EXISTS privacy_title text NOT NULL DEFAULT 'Privacy Policy',
  ADD COLUMN IF NOT EXISTS privacy_description text NOT NULL DEFAULT 'Your privacy is fundamental to SHORTSAL. This policy explains what data we collect and how we use it.',
  ADD COLUMN IF NOT EXISTS privacy_content text NOT NULL DEFAULT E'1. User Data Collection\nWe collect information you provide when creating an account (name, email, phone, date of birth) and information generated as you use SHORTSAL (videos you watch, likes, comments, shares, device type, IP address, and approximate location). This helps personalize your feed, secure your account, and improve our services.\n\n2. Cookies Usage\nSHORTSAL uses cookies and similar technologies to remember preferences, keep you signed in, analyze traffic, and deliver relevant content.\n\n3. Camera and Microphone Permissions\nTo record and upload videos, SHORTSAL requests access to your device camera and microphone. These permissions are used only while you are actively creating content.\n\n4. Content Upload Policy\nYou own the content you upload. By posting on SHORTSAL, you grant us a non-exclusive license to host, display, and distribute your videos on the platform.\n\n5. Account Safety\nWe protect your account with industry-standard encryption, secure password storage, and optional two-factor authentication.\n\n6. Ads and Analytics\nSHORTSAL may display ads served by trusted partners including Google AdSense. We use analytics to improve the experience.\n\n7. Contact\nFor privacy questions or to delete your account, contact us using the details on our Contact page.',

  ADD COLUMN IF NOT EXISTS terms_title text NOT NULL DEFAULT 'Terms & Conditions',
  ADD COLUMN IF NOT EXISTS terms_description text NOT NULL DEFAULT 'By using SHORTSAL you agree to the following terms. Please read carefully.',
  ADD COLUMN IF NOT EXISTS terms_content text NOT NULL DEFAULT E'1. User Responsibilities\nYou must be at least 13 years old to use SHORTSAL. You are responsible for your account security and all activity under your account.\n\n2. No Harmful or Illegal Content\nDo not post illegal, hateful, violent, sexually explicit, harassing content, or content that promotes self-harm, terrorism, or dangerous activities.\n\n3. Copyright Rules\nOnly upload content you own or have permission to use. We respond to valid DMCA takedown notices.\n\n4. Account Suspension\nSHORTSAL may suspend or terminate accounts that violate these terms, our Community Guidelines, or applicable law.\n\n5. Video Upload Rules\nVideos must comply with our content standards: appropriate length, original or licensed media, no misleading thumbnails, no spam.\n\n6. Platform Usage\nYou may not reverse-engineer, scrape, or exploit SHORTSAL. We may update these terms; continued use means acceptance.',

  ADD COLUMN IF NOT EXISTS about_title text NOT NULL DEFAULT 'About SHORTSAL',
  ADD COLUMN IF NOT EXISTS about_description text NOT NULL DEFAULT 'A creative short video platform built for the next generation of storytellers.',
  ADD COLUMN IF NOT EXISTS about_content text NOT NULL DEFAULT E'Our Mission\nSHORTSAL exists to empower everyone to express themselves through short-form video.\n\nWhat We Do\nSHORTSAL is a short video social platform where users upload, watch, like, comment, and share short videos. Smart recommendations surface content you love.\n\nOur Community\nInspired by TikTok and other leading creator platforms, SHORTSAL is home to artists, comedians, educators, athletes, and millions of everyday people.\n\nOur Vision\nWe are building the most creator-friendly short video platform in the world.',

  ADD COLUMN IF NOT EXISTS community_title text NOT NULL DEFAULT 'Community Guidelines',
  ADD COLUMN IF NOT EXISTS community_description text NOT NULL DEFAULT 'SHORTSAL is for everyone. These guidelines keep our community safe, respectful, and creative.',
  ADD COLUMN IF NOT EXISTS community_content text NOT NULL DEFAULT E'Be kind and respectful\nTreat every member of the community with kindness. Harassment, hate speech, or targeted attacks based on identity are not allowed.\n\nKeep it safe\nNo content that promotes self-harm, violence, dangerous challenges, or illegal activity.\n\nBe authentic\nDon''t impersonate others, spread misinformation, or use bots to inflate engagement.\n\nRespect privacy\nDon''t share another person''s private information or content without consent.\n\nNo spam or scams\nDon''t post repetitive content, misleading links, phishing attempts, or scams.\n\nReport what you see\nIf you see content that violates these guidelines, report it using the in-app tools.',

  ADD COLUMN IF NOT EXISTS earning_title text NOT NULL DEFAULT 'Earning Policy',
  ADD COLUMN IF NOT EXISTS earning_description text NOT NULL DEFAULT 'Learn how monetization works on SHORTSAL and when your channel becomes eligible to earn.',
  ADD COLUMN IF NOT EXISTS earning_content text NOT NULL DEFAULT E'Monetization Eligibility\nYour channel becomes eligible for monetization once you reach 800 followers and 100,000 (1 lakh) total views. Once both milestones are met, your channel will be reviewed and monetization will be enabled.\n\nWhen Earnings Start\nAfter your channel is monetized, you will start earning from ads shown on your videos, creator rewards, and brand partnership opportunities offered through SHORTSAL.\n\nPayout Information\nEarnings are calculated monthly. Once your balance reaches the minimum payout threshold, the amount is transferred to your linked payment method. You can view your earnings inside the creator dashboard.\n\nContent Requirements\nTo remain monetized, your content must follow our Community Guidelines and Terms & Conditions. Repeated violations, spam, reused content, or fake engagement will result in demonetization.\n\nPending Status\nWhile your channel is below the requirements (under 800 followers or under 100,000 views), it stays in pending status. You can keep uploading and growing your audience — monetization activates automatically once you qualify.\n\nTransparency\nAll earnings and view counts are tracked transparently. If you have any questions about your monetization status, contact our support team via the Contact page.';
